### ISSUE TITLE
Udostępnianie oferty przez wolontariusza

### ISSUE THREAD

**Issue by magul** [stxnext-csr/volontulo#14]
JAKO wolontariusz
CHCĘ móc udostępnić ofertę
ABY zainteresować nią innych.

**Comment by Yog** [comment]
fb g+ and twitter share buttons are alerady available
![image](https://cloud.githubusercontent.com/assets/432220/12515225/9a1cc19e-c127-11e5-803a-92f79f30fe9f.png)
