### ISSUE TITLE
No user login in header on user details page

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#182]
The user email is missing, but only on the user details page
![image](https://cloud.githubusercontent.com/assets/432220/10087985/ca308cb2-6317-11e5-9795-155c9c69e7d1.png)

**Comment by Yog** [comment]
same problem appears on offer edit page
http://localhost:8000/v/offers/WRK/1/edit

It might possibly be because both user page and offer edit page display user e-mail in the page content?

**Comment by magul** [comment]
In all pages listed bellow under 'user' variable template see UserProfile object instead User:
- organizations/view
- offers/create
- offers/edit
- me

**Comment by magul** [comment]
We need to develop more generic and sane way to pass user's information to template rendering engine.

**Comment by magul** [comment]
In UserProfile model we have OneToOneField field, so instead of passing raw UserProfile object into template engine we will pass User object and access UserProfile by user.userprofile attribute.
