### ISSUE TITLE
logged in user shouldn't see a login or register page

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#244]
If a user loggs in they shouldn't be able to see login or register page. If they go on `/login/` or `/register/` url, they should see their profile page instead. 
Also, any interface links to login or reqister page shouldn't be visible anywhere for logged in users

**Comment by filipgorczynski** [comment]
This has related #222 with unittests; it redirects to /me page when authorized user try to get to login page. The same should be done for /register page.

**Comment by magul** [comment]
@filipgorczynski we should logically separate redirect and showing links on page. They are separate issues.

**Comment by filipgorczynski** [comment]
Not get it. I wrote that logged in user should be redirected to another page when [s]he try to log in one more time. I don't understand logical separation of links... Are you talking about the case, when the user is logged in [s]he shouldn't see login/register links on page?

**Comment by magul** [comment]
@filipgorczynski 
- redirecting any request to /login and /register
- not showing links in rendered page to /login and /redirect

They are separate things - You can have page, that render link to /login, even it this link will immediately redirect to /me.

We should assure, that these links willn't be rendered, when user is logged in.
