### ISSUE TITLE
email header and footer content

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#265]
Every email header and footer should be the same most of the time. Only content is actually going to change. 
- prepare header
- prepare footer
- make existing templates use header and footer

**Comment by Yog** [comment]
Please fix image path in pr https://github.com/stxnext-csr/volontulo/pull/266

**Comment by magul** [comment]
@Yog there is some problem with Your pull request. See Travis logs for more info.

**Comment by Yog** [comment]
@magul fixed
