### ISSUE TITLE
Design email general text & look that will be used in every email

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#269]
pick the right colors and elements, text that makes sense to make emails look 'nice' ;)
- possible text slogan next to a logo
- text about not replying to an e-mail, because its just an info (like registration or password reset)
- volontulo text about legal/contact info

**Comment by wrk-zop** [comment]
Przyjdź do nas na dyżur doradczy do Centrum Bukowska 27/29, (róg ul. Bukowskiej i ul. Wawrzyniaka)
w każdy wtorek między godziną 16.00 a 18.00
lub w czwartek od 16,00 do 18.00.
w celu omówienia pracy wolontariusza.

**Comment by Justine1** [comment]
Zapraszamy do Centrum Wolontariatu na dyżury dla wolontariuszy i organizatorów wolontariatu. Odbywają się one w każdy wtorek w godz. 16:00 - 18:00 lub w czwartek w godz. 16:00 - 18:00 w Centrum Bukowska (ul. Bukowskiej 27/29). 

Z pozdrowieniami
Zespół Centrum Wolontariatu w Poznaniu
ul. Bukowska 27/29, 60-501 Poznań
tel. 61 85 30 930, 61 62 32 145
wolontariat@wrk.org.pl, www.wolontariat.wrk.org.pl

Wielkopolska Rada Koordynacyjna Związek Organizacji Pozarządowych (www.wrk.org.pl) należy do Ogólnopolskiej Sieci Centrów Wolontariatu i prowadzi Regionalne Centrum Wolontariatu w Poznaniu.

**Comment by Yog** [comment]
i have designed every email to look along tehse lines:
![image](https://cloud.githubusercontent.com/assets/432220/12450911/a38dcce8-bf86-11e5-94d7-0b5b03b55a57.png)
the middle part along with the icon is customizable for every email type.

**Comment by Yog** [comment]
This task includes work from #270 #271 #272 #273 #274
