### ISSUE TITLE
design email text & look for volunter_to_admin

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#273]

**Comment by Justine1** [comment]
Witaj

Dziękujemy za pytanie. Nasz doradca skontaktuje się z Tobą mailowo lub telefonicznie.
Zapraszamy rówenież na dyżury doradcze dla organizatorów wolontariatu. Odbywają się one w każdy wtorek w godz. 16:00 - 18:00 lub w czwartek w godz. 16:00 - 18:00 w Centrum Bukowska (ul. Bukowskiej 27/29).

Z pozdrowieniami
Zespół Centrum Wolontariatu w Poznaniu
ul. Bukowska 27/29, 60-501 Poznań
tel. 61 85 30 930, 61 62 32 145
wolontariat@wrk.org.pl, www.wolontariat.wrk.org.pl

Wielkopolska Rada Koordynacyjna Związek Organizacji Pozarządowych (www.wrk.org.pl) należy do Ogólnopolskiej Sieci Centrów Wolontariatu i prowadzi Regionalne Centrum Wolontariatu w Poznaniu.

**Comment by Yog** [comment]
this email is sent both to site admin and the sender and coz of that it appears so:
![image](https://cloud.githubusercontent.com/assets/432220/12482301/2f5e3000-c04f-11e5-9768-87e23021e7f2.png)
