### ISSUE TITLE
Kontakt wolontariusza z adminem

### ISSUE THREAD

**Issue by magul** [stxnext-csr/volontulo#32]
JAKO wolontariusz
CHCĘ móc skontaktować się z adminem
ABY rozwiewać wątpliwości, uzyskać info o wolontariacie.

KA
Przycisk "Zadaj pytanie" w różnych miejscach w systemie (link do kontaktu).
Formularz + automat mailingowy (imię, nazwisko, mail, telefon i pytanie).
Strona Kontakt.

**Comment by Yog** [comment]
this task should be done in conjuction with #98

**Comment by filipgorczynski** [comment]
Within this issue there is dropdown with VOLUNTEER or ORGANIZATION that allow contact with administrator - so it's connected with issue #30 .
