### ISSUE TITLE
appearance of offer create & edit page

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#321]
the pages should be roughly styled along http://ux.stxnext.pl/OS73UI/#p=edycja_oferty

**Comment by wrk-zop** [comment]
Wymagania, trzeba zmienić na Wymagania wobec wolontariusza. 
Zamiast lokalizacja - Miejsce odbywania wolontariatu.

**Comment by wrk-zop** [comment]
- "Przewidziany czas pracy wolontariusza"  i "Liczba wolontariuszy/wolontariuszek"

**Comment by Yog** [comment]
> Wymagania, trzeba zmienić na Wymagania wobec wolontariusza. 
> Zamiast lokalizacja - Miejsce odbywania wolontariatu.

and

> "Przewidziany czas pracy wolontariusza" i "Liczba wolontariuszy/wolontariuszek"

zrobione
Kontunuuję układania wygladu
