### ISSUE TITLE
images save to/are read from incorrect location

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#331]
uploaded images write to: `\volontulo_org\profile` or `\volontulo_org\gallery`
while system looks for them ... somewhere else?

**Comment by filipgorczynski** [comment]
There should be configured STATIC_\* and MEDIA_\* settings in django settings files:
in settings.py file define:

``` python
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
```

and create these diretories.
For statics after build with gulp there should be called:

``` shell
python manage.py collectstatic
```

that will collect all static from all INSTALLED_APPS and save them in /static/APP_NAMES/ dirs.
MEDIA_\* are used as the place for storing uploaded data - images, etc. so media subdirectories should be created on demand (usually first save).

**Comment by Yog** [comment]
did that, i have both

```
\volontulo_org\media
\volontulo_org\static
```

and

```
\volontulo_org\volontulo\volontulo\media
\volontulo_org\volontulo\volontulo\static
```

I have also ran the command `python manage.py collectstatic` which did copy some files to `\volontulo_org\static` but stuill the uploaded avatar doesn't show and writes to `\volontulo_org\media`, while i gues it should be `\volontulo_org\volontulo\volontulo\media`

**Comment by Yog** [comment]
some additional changes were needed:
http://dpaste.com/2K5FTNF
http://dpaste.com/2MRE69Z
