### ISSUE TITLE
User profile: decide collumns for tables with created offers and offers that user is taking part in

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#338]
the tables:
![image](https://cloud.githubusercontent.com/assets/432220/10730905/1d7e4dac-7bf3-11e5-838b-ce3c31989b20.png)

Lets decide:
- what columns are needed for every table
- if content of a collumn should be a link and where should it link to (example: title can link to offer details)
- buttons, if a table needs buttons that allows to do something (example: activate offer)

**Comment by Justine1** [comment]
"Oferty, w których zamierzasz wziąć udzał":
- "Tytuł oferty" - podlinkowany do treści ogłoszenia
- "Organizator" - nazwa organizacji/instytucji zgłaszającej akcję a nie jej mail
- w przypadku wolontariatu akcyjnego (któtkoterminowego/jednorazowego) - "Data akcji" - termin, w którym dana akcja się odbywa (jeden lub kilka dni, w zależności od akcji)
- w przypadki wolontariatu długoterminowego/stałego - "Data zgłoszenia" - dzień, w którym ochotnik zgłosił się na wolontariat
- dodatkowa kolumna - "Zadaj pytanie" - sformułowanie podlinkowane do formularza kontaktowego z organizatorem
- kolumny "Ropoczęcie akcji" i "Czas trwania" są niepotrzebne

"Lista ofert w tej organizacji":
- "Tytuł oferty" - podlinkowany do oferty w celu np. podgladu na stronie
- "Miejce" - OK
- zamiast "Czas obowiazywania" powinno być "Czas rekrutacji"
- zamiast "Akcja" powinno być "Oferta". W rozmowach z organizacjami i intytucjami posługujemy się najcześciej sformułowaniem "Oferta" i dlatego określenie "Akcja" może być dla nich mniej intuicyjne

Żeby nie używać za każdym razem długiego sformułowania organizacja/instytucja, korzystających z wolontariuszy moglibyśmy w sytemie nazwać "Organizatorami"

**Comment by Yog** [comment]
Jesli chodzi o 

> "Oferty, w których zamierzasz wziąć udzał"
- w jednej tabeli nie bardzo jest sens wrzucać oferty stałe i te z określoną akcją, bo nie ma jak ich wtedy opisać - musiały by byc osobne tabele  
  Może wobec tego to nie powinny być tabele, tylko takie panele ze zdjęciami jak na stronie głównej?
- nie nalezało by dodac tez kolumny "Miejsce" ?

**Comment by Yog** [comment]
> zamiast "Akcja" powinno być "Oferta". W rozmowach z organizacjami i intytucjami  posługujemy się najcześciej sformułowaniem "Oferta" i dlatego określenie "Akcja"  może być dla nich mniej intuicyjne

Tu chodzi o to, że to są akcje czyli operacje które można wykonać na danej ofercie
- Myślę, że najleopiej aby ta kolumna nie miała nazwy, bo buttony tłumacza się same

**Comment by Yog** [comment]
this task has been refined into  #359 and #360 
continue in these tasks
