### ISSUE TITLE
main page: sort offers by their end recruitment date and present start action date on an offer thumbnail

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#343]

**Comment by Yog** [comment]
For now we are going to sort offers by a different rule described in #340 

Only task remaining here is to make sure the start date is correct

**Comment by filipgorczynski** [comment]
I don't understand. How then offers sholud be sorted on home page? By weight or more specific criteria?

**Comment by Yog** [comment]
as comment https://github.com/stxnext-csr/volontulo/issues/343#issuecomment-155396156 specifies, sorting is done in the other task

displayed date is the start and end time for the offer action

thuis is solved
