### ISSUE TITLE
Add link to organization from offers list

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#422]
On offers list on url: `/offers` Every listed organization name should link to its organization name, linke so:

```
<a href="{% url 'organization_view' offer.organization.name|slugify offer.organization.id %}" class="btn btn-link">{{ offer.organization.name }}</a>
```

But then 'Test offers' list for account of admin. ' test fails. Find out why and fix it :)

**Comment by Yog** [comment]
make sure that https://github.com/stxnext-csr/volontulo/pull/420 pR is merged first, or do it on its branch

**Comment by mkwiat79** [comment]
starting, however not very happy with this one :)

**Comment by zuzannawiler** [comment]
@mkwiat79 any questions - ask Piotr Rorot ;)
