### ISSUE TITLE
volontuloapp.org Can't accept cookies

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#427]
Somehow it is not possible to accept them. This problem is present only there.  
Mine works alright https://volontulo-yoga1.c9users.io/ It is ran with:
`python manage.py runserver --insecure --settings=volontulo_org.settings.dev $IP:$PORT`

**Comment by Yog** [comment]
here you have got another bug with it https://github.com/stxnext-csr/volontulo/issues/446

**Comment by magul** [comment]
#446 has a screnshot and is a little more detailed. I'm closing this one as duplicate.

**Comment by Yog** [comment]
use duplicate label instead and solve the task already ;d
