### ISSUE TITLE
Delete the e-mail field in "Moje konto" in the "Profil" section

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#445]
Once an account is created, the e-mail under which it was created cannot be changed.
Since the user's email address is visible on every site after logging in, the field "Email" in the "Profil" section needs to be removed as to not create confusion.

![](https://cloud.githubusercontent.com/assets/15927677/13283605/e39a2e34-daee-11e5-86b8-8824b9f61cc9.png)

**Comment by zuzannawiler** [comment]
![screenshot-at-12-01-12](https://cloud.githubusercontent.com/assets/15927677/13283605/e39a2e34-daee-11e5-86b8-8824b9f61cc9.png)

http://volontuloapp.org/me

**Comment by filipgorczynski** [comment]
I'll take this one.
