### ISSUE TITLE
A user cannot agree to accept cookies

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#446]
Even though the information to accept cookies is displayed, clicking on the acceptance button does nothing.
The button must be active and the information needs to be hidden after accepting cookies.

**Comment by zuzannawiler** [comment]
![screenshot-at-09-39-57](https://cloud.githubusercontent.com/assets/15927677/13281720/ad9ac0c2-dae5-11e5-935b-5335bc5e2cb3.png)

**Comment by Yog** [comment]
this is likely problem with volontuloapp.org only as described in #427

**Comment by filipgorczynski** [comment]
I'll take this one.

**Comment by filipgorczynski** [comment]
![worksonmymachine](https://cloud.githubusercontent.com/assets/467026/13362537/767ab430-dcc5-11e5-9df4-3464c3898c50.jpg)

Problem is that this script returns 404 on production - I have no access there so I can't descibe real problem. In my opinion there should be JavaScript file in frontend directory and this file should be "copied" to static (with it's directory structure) on `gulp build`.

@magul: Give me feedback after production release.
