### ISSUE TITLE
The news site needs to be disabled

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#448]
As for now there are no news to be posted on the website, the whole sub-site http://volontuloapp.org/pages/site-news needs to be disabled.

**Comment by zuzannawiler** [comment]
![screenshot-at-12-07-33](https://cloud.githubusercontent.com/assets/15927677/13283663/3ec68384-daef-11e5-81c6-2295b21e382e.png)

This view is present on every sub-site.

**Comment by KrzysztofMadejski** [comment]
Biorę to! @magul

**Comment by w1stler** [comment]
Works fine.
