### ISSUE TITLE
There should be a STREFA WOLONTARIUSZA section in the footer

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#450]
The last section in the footer should be renamed from OFERTY to STREFA WOLONTARIUSZA with sub-sites for volunteers. 
The section should contain:
Załóż konto (http://volontuloapp.org/register)
Lista aktualnych ofert (http://volontuloapp.org/offers)
Archiwum ofert (http://volontuloapp.org/offers/archived)
Lista organizacji i instytucji (http://volontuloapp.org/organizations)
FAQ dla wolontariuszy (http://volontuloapp.org/pages/faq-volunteers)
Przyjdź na dyżur (http://volontuloapp.org/office)

![screenshot-at-11-00-50](https://cloud.githubusercontent.com/assets/15927677/13350491/9c9365d0-dc80-11e5-9d90-d17bc79de9df.png)

**Comment by zuzannawiler** [comment]
![screenshot-at-12-11-42](https://cloud.githubusercontent.com/assets/15927677/13283732/d7a648d2-daef-11e5-987b-c18e8b44bd4b.png)

**Comment by KrzysztofMadejski** [comment]
Biorę to @magul

**Comment by KrzysztofMadejski** [comment]
@zuzannawiler http://volontuloapp.org/office page doesn't exist. Is it ok per this issue? Should I create failing test for it?

**Comment by zuzannawiler** [comment]
yes. should be done in #451
