### ISSUE TITLE
A sub-page http://volontuloapp.org/office needs to be created

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#451]
In order to get in touch with the WRK
As a user
I want to have the contact info on the http://volontuloapp.org/office

AC
The information should be as follows:

Zapraszamy do naszego biura, które znajduje się przy ul. Bukowskiej 27/29 w Poznaniu.
Dyżury dla wolontariuszy oraz organizacji i instytucji współpracujących z wolontariuszami odbywają się w każdy **wtorek w godz. 16.00-18.00** i **czwartek w godz. 16.00-18.00**. 

Możesz też skontaktować się z nami mailowo: wolontariat@wrk.org.pl lub telefonicznie: 61 85 30 930.

Zachęcamy do kontaktu :)

**Comment by zuzannawiler** [comment]
![screenshot-at-12-12-49 kopia](https://cloud.githubusercontent.com/assets/15927677/13283745/f51c7940-daef-11e5-9ad1-e869391c363d.png)

**Comment by KrzysztofMadejski** [comment]
I take it as the dependency of #450

**Comment by KrzysztofMadejski** [comment]
@zuzannawiler can it be available as `/pages/office` or should I short link-it (anyways it should be static page, right?)

**Comment by KrzysztofMadejski** [comment]
The same question for #490

**Comment by nbbn** [comment]
I'm doing it. URL is specified in #488

**Comment by zuzannawiler** [comment]
@KrzysztofMadejski I get 404 error when I enter http://volontuloapp.org/pages/office. Why is that? Is it uploaded on production or not?

**Comment by w1stler** [comment]
Any styling here? Currently it doesn't look nice. 

![image](https://cloud.githubusercontent.com/assets/17498341/13368539/8d30b212-dceb-11e5-88f0-073e046a89b9.png)

**Comment by zuzannawiler** [comment]
I agree, but there is not much time left, unfortunately...
