### ISSUE TITLE
Event picture is not displayed in the event's details page

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#453]
The picture uploaded during event creation needs to be displayed on the event's details page.

**Comment by zuzannawiler** [comment]
![screenshot-at-09-22-32](https://cloud.githubusercontent.com/assets/15927677/13281748/d2ff4f04-dae5-11e5-8f13-812e56b528f1.png)

**Comment by Yog** [comment]
this is likely problem with volontuloapp.org but it should be investigated
