### ISSUE TITLE
Calendar and clock in offer creation

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#456]
In order to use the right format for the offer dates
As an organization
I want to have a calendar and a clock in these fields to choose a date and time precisely

**Comment by zuzannawiler** [comment]
![screenshot-at-09-34-43](https://cloud.githubusercontent.com/assets/15927677/13280948/37084924-dae1-11e5-816c-ca8d9143515b.png)

**Comment by zuzannawiler** [comment]
![screenshot-at-09-34-43](https://cloud.githubusercontent.com/assets/15927677/13281764/efdac054-dae5-11e5-9ea7-c4dd04efe571.png)

**Comment by Yog** [comment]
this is duplicate of https://github.com/stxnext-csr/volontulo/issues/417

**Comment by magul** [comment]
I'm closing it as duplicate of #417. @zuzannawiler if there is any information missing in #417, please add it there.
