### ISSUE TITLE
"Sidebar block" is empty and visible

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#458]
On sub-sites
http://volontuloapp.org/organizations/create
http://volontuloapp.org/pages/site-news
there is an empty space "Sidebar block" on the left visible for the user. Since there is no content there, the sidebar block should be hidden.

![screenshot-at-09-15-13](https://cloud.githubusercontent.com/assets/15927677/13281801/24fb2fe4-dae6-11e5-8106-386dbc819d46.png)

**Comment by Yog** [comment]
use col1 layout instead of col2
