### ISSUE TITLE
3 banners on the homepage should be hidden

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#459]
There are 3 buttons with a place for a picture on the homepage visible for a logged-in user.
They are either unnecessary or duplicate other page content.
All of them should be hidden and not visible at any time, for any type of user.

![screenshot-at-09-23-03](https://cloud.githubusercontent.com/assets/15927677/13281838/4c853834-dae6-11e5-942d-18c6c97c13bb.png)

**Comment by magul** [comment]
to be confirmed with @doslizlo

**Comment by tiriana** [comment]
I take it - @tiriana

**Comment by tiriana** [comment]
@zuzannawiler please move to in progress

**Comment by tiriana** [comment]
@zuzannawiler Please move to 'pull request'
