### ISSUE TITLE
Prepare home page for an admin

### ISSUE THREAD

**Issue by RW-WiktorBakalarski** [stxnext-csr/volontulo#465]
In order to see the homepage just as a user sees it
As an admin
I want to have the homepage view on the http://volontuloapp.org/

AC:
- Admin can see the same home page as an user

![](https://cloud.githubusercontent.com/assets/15927677/13283842/84009a6a-daf0-11e5-9708-8465230c6f7c.png)

Currently, the admin sees admin panel on the homepage and has no possibility to view the regular homepage logged in as admin. The admin panel should be moved to another page (#466)

**Comment by zuzannawiler** [comment]
![screenshot-at-12-17-07](https://cloud.githubusercontent.com/assets/15927677/13283842/84009a6a-daf0-11e5-9708-8465230c6f7c.png)

**Comment by Ziachu** [comment]
in progress... ;)

**Comment by w1stler** [comment]
Works as expected. @zuzannawiler @bakalaw - ready to sign-off.
