### ISSUE TITLE
As an organisation I can see event status of my offers

### ISSUE THREAD

**Issue by RW-WiktorBakalarski** [stxnext-csr/volontulo#468]
A user's organization's offers are visible on http://volontuloapp.org/organizations/wilerorg/6 and http://volontuloapp.org/me. 
The columns should be ordered (from the left): picture, title, place, time, status, edit button (optional, only for unpublished offers).

AC
1. Additional column between time and optional edit button is added
2. The column is named "Status"
3. The possible statuses are: unpublished/published/rejected
4. The changes are introduced in both places mentioned above

**Comment by zuzannawiler** [comment]
![screenshot-at-12-18-56](https://cloud.githubusercontent.com/assets/15927677/13283904/f3d98dc4-daf0-11e5-97ae-5fc8c98b04b8.png)

A user's organization's offers are visible on http://volontuloapp.org/organizations/wilerorg/6 and http://volontuloapp.org/me. In both places the user can:
edit an offer (until it's activated by the admin)
see the status of an offer (Active/Archived)

**Comment by magul** [comment]
add another column with status
