### ISSUE TITLE
Inactive user can log in with the credentials given during registration

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#469]
In order to fully use the website
As a registered user
I want to use my account without the need to activate the account.

AC
Credentials given during registration are used to login for inactive users

**Comment by magul** [comment]
@zuzannawiler - we want to activate account before first join of offer. Please update descrption.

**Comment by zuzannawiler** [comment]
The current state on the website is that a user must activate the account before logging in.
