### ISSUE TITLE
Login and register view are on the same page

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#483]
Login and register view should be places side by sidde on the same sub-site.

AC
Register view is first on the left, login is on the right
The address of this sub-page is http://volontuloapp.org/login
Both login and register options (top left) are linked to http://volontuloapp.org/login

![screenshot-at-09-29-15 kopia](https://cloud.githubusercontent.com/assets/15927677/13354059/ba7006d6-dc98-11e5-951d-e9d0b0f67919.png)

**Comment by w1stler** [comment]
Works fine. @zuzannawiler, @bakalaw - ready to sign-off.
