### ISSUE TITLE
As an anonymous user I want to sign up for an offer

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#484]
When an anonymous user wants to sign up for an offer and fills in all the required fields, when he confirms the system can:
1. recognize the user as an already registered user and the login page is displayed with an already filled in email (taken from the application for an offer). After logging in, the user is automatically signed up for the offer.
2. recognize the user as a new user and the register page is displayed with an already filled in email (taken from the application for an offer). After registering the information about sending verification email is sent. After verification and logging into the account the user is automatically signed up for the offer.
3. recognize the user as a registered, but not verified user, then the request to verify the email is displayed. After verification and logging into the account the user is automatically signed up for the offer.

**Comment by Yog** [comment]
1. 
2. user shouldnt see register page, because that is overcomplicated. We might implement it if we have problem with fake applying. 
   instead we should probably inform user about what hapened in an email. It can be separate e-mail similiar to rigister/verify email template
