### ISSUE TITLE
"Wyloguj" button needs to be hidden

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#486]
The log out button that is at the bottom of the http://volontuloapp.org/me page needs to be hidden since there is a log out button at the top of the page. There is no need to duplicate this functionality.
![screenshot-at-10-32-08](https://cloud.githubusercontent.com/assets/15927677/13348531/5ee62ea4-dc74-11e5-857d-243f18754031.png)

**Comment by w1stler** [comment]
As mentioned on review, works fine.
