### ISSUE TITLE
There should be an INFORMACJE section in the footer

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#489]
The first section in the footer should be renamed to INFORMACJE with sub-sites regarding the general idea of the website.

The section should contain:
Strona główna (http://volontuloapp.org)
Załóż konto (http://volontuloapp.org/register)
Kontakt z administratorem (http://volontuloapp.org/contact)
O nas (http://volontuloapp.org/o-nas)
Zapisz się do newslettera (http://volontuloapp.org/newsletter)
Regulamin (http://volontuloapp.org/pages/regulations)

![screenshot-at-11-00-50](https://cloud.githubusercontent.com/assets/15927677/13350856/13706638-dc83-11e5-8b8a-d6bfafc07fdd.png)

**Comment by tiriana** [comment]
@zuzannawiler if this is not taken - I can do it.

**Comment by magul** [comment]
@tiriana, do it!

**Comment by tiriana** [comment]
@zuzannawiler assign me please

**Comment by zuzannawiler** [comment]
Sorry, it seems I cannot do it. But since you have commented on it then it should be fine.

**Comment by tiriana** [comment]
ok

**Comment by magul** [comment]
@tiriana because of some problems in github permissions, person without write permission to repo cannot be assigned to issue. Sorry :(

**Comment by tiriana** [comment]
@magul - I'm creating placeholders for pages as well

**Comment by tiriana** [comment]
in review: #506

**Comment by tiriana** [comment]
@zuzannawiler please move to next col

**Comment by magul** [comment]
@zuzannawiler - `o-nas` should also be in `/pages/` because it will also be a static page.

**Comment by magul** [comment]
@tiriana could You make a fast fix for this `o-nas` thing?

**Comment by w1stler** [comment]
Works as expected.

**Comment by w1stler** [comment]
@zuzannawiler, @magul - ready to sign-off.
