### ISSUE TITLE
A sub-page http://volontuloapp.org/o-nas needs to be created

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#490]
A sub-page with the information about Volontulo and WRK needs to be created.

AC
On the sub-site this content needs to be added:

Lubisz nowe wyzwania? Chcesz pomagać innym? Zależy Ci na rozwoju? Szukasz wolontariuszy? Jeśli choć na jedno z tych pytań opowiedziałeś/aś twierdząco wolontariat to odpowiedź dla Ciebie! Zgłoś się do Poznańskiego Centrum Wolontariatu prowadzonego przez Wielkopolską Radę Koordynacyjną Związek Organizacji Pozarządowych. Naszym celem jest pomoc we wzajemnym odnalezieniu się ludzi, którzy chcą realizować się jako wolontariusze/szki oraz organizacji i instytucji, które takich osób poszukują. 

Wolontariat to niesamowita okazja do zdobycia nowych doświadczeń, rozwoju swoich umiejętności i kompetencji, poznania innych ludzi. To także świadomość, że to co robisz ma sens!

**KIM JESTEŚMY?**

Wielkopolska Rada Koordynacyjna Związek Organizacji Pozarządowych jest dobrowolnym związkiem organizacji pozarządowych, który został utworzony w 1990 roku z inicjatywy kilkudziesięciu organizacji społecznych. Dziś jesteśmy największym związkiem w Wielkopolsce z zrzeszamy ponad 200 fundacji i stowarzyszeń z całego regionu. Poprzez swoją działalność kształcimy proobywatelskie i proaktywne postawy mieszkańców i mieszkanek Wielkopolski. Jako lider ruchu obywatelskiego w regionie inspirujemy do działań w obszarze „małych ojczyzn”. Uwrażliwiamy na potrzeby i problemy innych. Edukujemy, doradzamy, animujemy, wspieramy zarówno grupy formalne jak i nieformalne oraz niezrzeszonych aktywistów…

Od lat działamy na rzecz:
– wzmocnienia postaw obywatelskich,
– inicjowania i pomocy w uruchomieniu nowych społecznych inicjatyw,
– animowania wolontariatu,
– współpracy międzynarodowej i wymiany doświadczeń związanych z funkcjonowaniem sektora obywatelskiego.

W swoim działaniu kierujemy się wzajemnym wsparciem, partnerstwem, otwartą komunikacją, zaufaniem.

Od 2012 roku należymy do Ogólnopolskiej Sieci Centrów Wolontariatu i prowadzimy w Wielkopolsce Regionalne Centrum Wolontariatu koordynujące sieć 17 Lokalnych Centrów Wolontariatu. Jeśli chcesz założyć Lokalne Centrum Wolontariatu w swojej miejscowości, również zgłoś się do nas. Przygotujemy Ciebie i Twoją organizację.

W Poznaniu znajdziesz nas na ul. Bukowskiej 27/29, gdzie prowadzimy Poznańskie Centrum Wolontariatu i pomagamy łączyć wolontariuszy z organizatorami wolontariatu.

Więcej informacji o nas znajdziesz na www.wrk.org.pl.

**Comment by w1stler** [comment]
1. Two spaces before this sentence: "Uwrażliwiamy na potrzeby i problemy innych."

**Comment by zuzannawiler** [comment]
Good catch! Updated.

**Comment by KrzysztofMadejski** [comment]
I take it @magul

**Comment by tiriana** [comment]
@zuzannawiler Placeholder is already made in #506

**Comment by KrzysztofMadejski** [comment]
Should be moved to `pull requests`
