### ISSUE TITLE
"Kolejność ofert strony głównej" should be changed to "Kolejność ofert na stronie głównej"

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#493]
In the admin panel, there is a button that is linked to http://volontuloapp.org/offers/reorder/. The name on this button is "Kolejność ofert strony głównej" and it should be changed to "Kolejność ofert na stronie głównej".
![screenshot-at-17-07-44](https://cloud.githubusercontent.com/assets/15927677/13357611/8206f652-dcab-11e5-8449-74adb34db3a4.png)

**Comment by BernadetaNegra** [comment]
In progress.

**Comment by w1stler** [comment]
Label is changed, but apparently nothing happens after clicking on this button.

**Comment by zuzannawiler** [comment]
how come? when I click on it i get to http://volontuloapp.org/offers/reorder/

**Comment by w1stler** [comment]
From the main page -> it redirects properly to /offers/reorder. But from the UX perspective, buttons might be a bit misleading. 

I guess the buttons should be visibile not only on /offers/reorder/ & main page, but also on /offers/ and /offers/archived then.

**Comment by zuzannawiler** [comment]
there is a ticket for that. This one is just for renaming

**Comment by w1stler** [comment]
Then "looks good" would be appropriate expression. ;-)
