### ISSUE TITLE
An active logged out user wants to sign up for an offer 

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#495]
After filling in the form to sign up for an offer, the system recognizes a user as an active user, moves him/her to the login page with the email already filled in and the information at the top of the page "Zaloguj się, aby zapisać się do oferty" is displayed.
After logging in, the user gets a confirmation "Zgłoszenie chęci uczestnictwa zostało wysłane." and is already signed for the offer.

**Comment by gruszks** [comment]
Login form will not be automatically filled with email address.

This is wrong, user should explicitly sign for offer:
After logging in, the user gets a confirmation "Zgłoszenie chęci uczestnictwa zostało wysłane." and is already signed for the offer.
