### ISSUE TITLE
A new user wants to sign up for an offer

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#497]
After filling in the form to sign up for an offer, the system recognizes a user as a new user, moves him/her to the register page with the email already filled in and the information at the top of the page "Zarejestruj się, aby zapisać się do oferty" is displayed.
After registering and activating the account, the user gets a confirmation "Zgłoszenie chęci uczestnictwa zostało wysłane." and is already signed for the offer.

**Comment by gruszks** [comment]
Registration form will not be automatically filled with email address.

This is wrong, user should explicitly sign for offer:
After registering and activating the account, the user gets a confirmation "Zgłoszenie chęci uczestnictwa zostało wysłane." and is already signed for the offer.
