### ISSUE TITLE
Add logos in the footer

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#498]
WRK's, STX's and Koduj dla Polski's logo should be added in the footer, linked to the adequate websites.
Visualisation attached, assets on the way. The sub-footer is white because all logos compose with this color fine.
Please add the line "Ten serwis powstał wspólnym wysiłkiem we współpracy pomiędzy" above the logos as shown in the vis.
![a2484472-dcd6-11e5-9e27-34fa2107913b](https://cloud.githubusercontent.com/assets/15927677/13365716/08feb908-dcd7-11e5-8a0a-46b8eae2a790.png)

Assets:
![c13736ee-dcc8-11e5-9403-a13bf929e5db](https://cloud.githubusercontent.com/assets/15927677/13363383/65f1762c-dcc9-11e5-8372-67b8ef431f99.png)
![c13672cc-dcc8-11e5-9569-4b5fd3f3d35b](https://cloud.githubusercontent.com/assets/15927677/13363392/678f3136-dcc9-11e5-96dc-98e8ed2ce71c.png)
![c1369428-dcc8-11e5-992c-9b7486da389d](https://cloud.githubusercontent.com/assets/15927677/13363397/69851988-dcc9-11e5-8024-e96d1612ecf8.png)
![67629984-dcd6-11e5-911a-4b5163e04e78](https://cloud.githubusercontent.com/assets/15927677/13365648/9399793c-dcd6-11e5-86f2-09c89be01ffe.png)

**Comment by tiriana** [comment]
@zuzannawiler is It taken?

**Comment by zuzannawiler** [comment]
it is not in the backlog. this ticket is not prepared yet. please, take tickets from backlog column.

**Comment by tiriana** [comment]
@zuzannawiler I can't find link to it...

**Comment by magul** [comment]
@doslizlo Could You provide this assets?

**Comment by magul** [comment]
@tiriana I'm just writing to You on gitter

**Comment by zuzannawiler** [comment]
@doslizlo until it is clear how it should look like, this should not be at the top of the backlog. Are you working on it? Do you have any idea how it should look like?

**Comment by doslizlo** [comment]
Let's add these logos as an additional line in the footer. I'll prepare a quick visualisation. Also working on the assets.

**Comment by doslizlo** [comment]
Visualisation attached, assets on the way. The sub-footer is white because all logos compose with this color fine.
Please add the line "Ten serwis powstał wspólnym wysiłkiem we współpracy pomiędzy" above the logos as shown in the vis.

![image](https://cloud.githubusercontent.com/assets/556392/13362902/14a25e82-dcc7-11e5-808f-fe914089ab6b.png)

**Comment by doslizlo** [comment]
...and da assets:
![footer-logo-wrk](https://cloud.githubusercontent.com/assets/556392/13363259/c13672cc-dcc8-11e5-9569-4b5fd3f3d35b.png)
![footer-logo-kdp](https://cloud.githubusercontent.com/assets/556392/13363260/c1369428-dcc8-11e5-992c-9b7486da389d.png)
![footer-logo-stx](https://cloud.githubusercontent.com/assets/556392/13363261/c13736ee-dcc8-11e5-9403-a13bf929e5db.png)

**Comment by zuzannawiler** [comment]
ticket updated.

**Comment by tiriana** [comment]
@zuzannawiler I take it - @tiriana

**Comment by zuzannawiler** [comment]
@tiriana wait for another logo!

**Comment by tiriana** [comment]
@zuzannawiler np, I just started, you can add it in the meantime

**Comment by doslizlo** [comment]
And here comes the 4th logo. 
![footer-logo-komitywa](https://cloud.githubusercontent.com/assets/556392/13365630/67629984-dcd6-11e5-911a-4b5163e04e78.png)

**Comment by doslizlo** [comment]
Just a quick vis with the fourth one:
![image](https://cloud.githubusercontent.com/assets/556392/13365660/a2484472-dcd6-11e5-9e27-34fa2107913b.png)

**Comment by zuzannawiler** [comment]
ticket decription updated

**Comment by tiriana** [comment]
@doslizlo What is the font size for "Ten serwis powstał wspólnym wysiłkiem we współpracy pomiędzy"?

**Comment by tiriana** [comment]
@doslizlo And font color?

**Comment by tiriana** [comment]
@zuzannawiler What is the link for Komitywa?

**Comment by zuzannawiler** [comment]
@doslizlo  What is the link for Komitywa?

**Comment by tiriana** [comment]
@zuzannawiler I'll use this one

https://www.facebook.com/KOMITYWA.org/

komitywa.org redirects to some strange stuff
