### ISSUE TITLE
Regulamin

### ISSUE THREAD

**Issue by magul** [stxnext-csr/volontulo#56]
JAKO Wolontariusz
CHCĘ wiedzieć, na jakich zasadach działa serwis
ABY móc się do nich dostosować.

**Comment by doslizlo** [comment]
Dodałem do MVP ze względu na wymóg formalnoprawny.

**Comment by magul** [comment]
Czy my mamy jakiś wzorcowy regulamin? Ma być brany z bazy?

**Comment by doslizlo** [comment]
O ten regulamin musimy zapytać WRK - będzie musiał powstać z pomocą prawnika.
Z punktu widzenia systemu może to być w MVP wersja statyczna, nawet nie zaciągana z bazy i nieedytowalna przez administratora. Regulaminy zmieniają się raczej rzadko.
