### ISSUE TITLE
Statusy ofert

### ISSUE THREAD

**Issue by magul** [stxnext-csr/volontulo#62]
- [Nowa] - gdy oferta została dodana, ale jeszcze nie zatwierdzona przez operatora,
- [Aktywna] - gdy oferta została dodana przez organizację i zatwierdzona przez operatora, wolontariusze mogą się na nią zgłaszać,
- [Zakończona] - gdy został spełniony co najmniej jeden z warunków: 
  - uzyskano pełne wysycenie wolontariuszami (liczba osób zdefiniowana w szczegółach podczas jej dodawania),
  - upłynął okres rekrutacji wolontariuszy (okres zdefiniowany w szczegółach oferty podczas jej dodawania), 
  - oferta została oznaczona jako Zakończona przez operatora.
- [Zawieszona] - gdy oferta została oznaczona jako Zawieszona przez operatora, na przykład w wyniku zgłoszenia nadużycia z nią związanego lub innego zdarzenia wymagającego czasowego zawieszenia jej publikacji oraz rekrutacji; taka oferta nie wyświetla się w portalu.
- [Zamknięta] - gdy oferta została oznaczona jako Zamknięta przez operatora i nie jest planowane jej ponowne przywrócenie do wyświetlania.

**Comment by filipgorczynski** [comment]
As [project wiki](https://github.com/stxnext-csr/volontulo/wiki/Offer-related-statuses-in-Volontulo) says it's gonna be different approach here.
It must be definitely finished before many other issues.
